from pydantic import BaseModel


class ReportRequest(BaseModel):
    report_title: str
    report_description: str


class ReportGenerator:
    def generates_report(self) -> str:
        return "This is a sample report generated by the ReportGenerator."

    def ask_question(self, purpose: str, findings: str):
        return {"Purpose": purpose, "Findings": findings}
