from pydantic import dataclasses

@dataclasses.dataclass()
class ReportGenerator:
    def generates_report(self) -> str:
        return "This is a sample report generated by the ReportGenerator."

    def ask_question(self):
        question1 = "What is the purpose of this report?"
        answer1 = input(question1)

        question2 = "What are the main findings from the data?"
        answer2 = input(question2)

        return {"Purpose": answer1, "Findings": answer2}
